tap "elastic/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "bat"
brew "exa"
brew "git"
brew "httpie"
brew "nvm"
brew "python@3.9"
brew "redis", restart_service: true
brew "elastic/tap/elasticsearch-full"
cask "gitkraken"
cask "google-chrome"
cask "visual-studio-code"
